- name: update apt
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
<<<<<<< HEAD

- name: add backports repo
  sudo: yes
  copy:
      src: backports.list
     dest: /etc/apt/sources.list.d/backports.list
    owner: root
    group: root
     mode: 0644
=======
>>>>>>> 20ff0e4378b16f498e257c85f043079f8f65e646
