- name: install packages
  sudo: yes
  with_items: resume_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install pip packages
  sudo: yes
  pip:
    requirements: "{{ requirements_path }}"

- name: migrate DB
  command: python manage.py migrate
  args:
    chdir: "{{ api_path }}"

- name: migrate db
  sudo: yes
  sudo_user: vagrant
  django_manage:
    command: migrate
    app_path: /vagrant/projects

- name: put api/bin in path
  template:
    src: profile.j2
    dest: ~/.profile
